### ISSUE TITLE
Why do I get a sense, that you have simply copy the code from some upstream type ?

### ISSUE THREAD

**Issue by ashish1099** [shaheena86/puppet-type-provider#3]
Reasons.

1. This file https://github.com/shaheena86/puppet-type-provider/blob/master/optionaltypeprovider.rb has immense lint problem and this is a simple pp file and types and provider.
2. No explanation of the code

**Comment by shaheena86** [comment]
Yes. This code is being used on a production server at some xyz... organisation. I have checked on my VM for testing and understanding its functionality and workflow and hence added it to the GIT for my reference,

**Comment by ashish1099** [comment]
So this took 2 weeks for you to complete ?

Moreover thats not what we agreed.
We wanted you to write the code and not copying it from somewhere else.
If you don't know how, show us how much you can do it, take help from us from internet.

What do you think of this ?

**Comment by shaheena86** [comment]
You can check the type.rb and provider.rb files. That is something which I have taken help from the internet and tried to do. I have told above that the file is added for my reference.

Honestly... I don't know to code and I had told you the same when we had the telephonic conversation twice.
I have worked as a system admin and I have used the existing modules provided by puppetlabs on the servers.

Regarding - What do you think of this ?
-- I would just like to thank you for giving me this assignment because I really came across and read a lot of stuff about puppet. 

Again, I am looking forward towards automation but regarding coding it still on my learning part.
